// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjktcmpxadxmymgafeaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqa3RjbXB4YWR4bXltZ2FmZWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDcyOTIsImV4cCI6MjA2NTIyMzI5Mn0.U96AlUkAdT1ptvXKZgH0bQt1PEz_abk2eO32lPk0WwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);